### PR TITLE
fix render agent pos bug

### PR DESCRIPTION
**Pull request by wwxFromTju**
fix render agent pos bug.

more detail see:
https://github.com/openai/neural-mmo/issues/5#issue-417233063

### CODE REVIEW

**Comment by jsuarez5341** [comment]
Thanks for the pull req! I actually spent about an hour trying to reproduce the issue -- I'd be somewhat surprised if it's really just a straight off by one error on the overall position. I'll need to set aside a bit of time to test to make sure this fix doesn't result in desync anywhere else -- will likely merge it on Monday.

**Comment by jsuarez5341** [comment]
Funny -- I could not reproduce the issue earlier, but this patch causes exactly the issue that was described. You've confirmed that this actually fixes the issue on your setup?

**Comment by wwxFromTju** [comment]
I tested the code in Ubuntu and macos, and then used Chrome to render, all of which have the above problems.

Are you using the code for this repository? It seems that you have cleaned up the code and placed it on github, which may be a bug in the github version.

**Comment by kumarict** [comment]
This fix worked for me.

**Comment by jsuarez5341** [comment]
No longer relevant with no client. Closing

**Pull request closed without merging**
